### ISSUE TITLE
java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider could not be instantiated

### ISSUE THREAD

**Issue by senchzzZ** [hzdavid/jmockit.cn#26]
JDK1.7
Spring4
在做controller单测时，mock静态方法试了好几种方式（mockUp和Expectations）都不行，报java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider could not be instantiated这个错误，紧接着就是：
`
java.lang.NullPointerException
	at mockit.internal.util.ClassLoad.loadByInternalName(ClassLoad.java:31)
	at mockit.internal.ClassLoadingBridge.setBridgeFields(ClassLoadingBridge.java:105)
	at mockit.internal.ClassLoadingBridge.getHostClassName(ClassLoadingBridge.java:96)
	at mockit.internal.BaseClassModifier.generateCodeToObtainInstanceOfClassLoadingBridge(BaseClassModifier.java:171)
	at mockit.internal.faking.FakedClassModifier.generateCallToFakeMethodThroughClassLoadingBridge(FakedClassModifier.java:250)
	at mockit.internal.faking.FakedClassModifier.generateCallToFakeMethod(FakedClassModifier.java:239)
	at mockit.internal.faking.FakedClassModifier.generateConditionalCallForFakedMethod(FakedClassModifier.java:211)
	at mockit.internal.faking.FakedClassModifier.generateDynamicCallToFake(FakedClassModifier.java:166)
	at mockit.internal.faking.FakedClassModifier.visitMethod(FakedClassModifier.java:118)
	at mockit.external.asm.ClassReader.readMethod(ClassReader.java:770)
	at mockit.external.asm.ClassReader.readFieldsAndMethods(ClassReader.java:596)
	at mockit.external.asm.ClassReader.accept(ClassReader.java:503)
	at mockit.internal.faking.FakeClassSetup.modifyRealClass(FakeClassSetup.java:97)
	at mockit.internal.faking.FakeClassSetup.redefineMethods(FakeClassSetup.java:77)
	at mockit.MockUp.redefineMethods(MockUp.java:197)
	at mockit.MockUp.redefineClassOrImplementInterface(MockUp.java:182)
	at mockit.MockUp.<init>(MockUp.java:129)
	at cn.px.dxs.web.controller.h5.AbnormalControllerTest$1.<init>(AbnormalControllerTest.java:86)
	at cn.px.dxs.web.controller.h5.AbnormalControllerTest.getPosVersionAll(AbnormalControllerTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
`

写法如下：
`
new MockUp<WebUtil>(){
            @Mock
            public Map<Long, Restaurant> getHotelInfoCache(HttpServletRequest request){
                Map<Long, Restaurant> map = new HashMap<>();
                map.put(300000094l,new Restaurant());
                return map;
            }
        };

        /*new Expectations(WebUtil.class){
            {
                WebUtil.getHotelInfoCache((HttpServletRequest) any);
                Map<Long, Restaurant> map = new HashMap<>();
                map.put(300000094l,new Restaurant());
                result = map;
            }
        };*/
`
求大神赐教。

**Comment by senchzzZ** [comment]
jmockit包引在Junit下面了，调整一下俩包的顺序好了
